version: 2
sources:
  - name: raw
    database: my-first-project-1-414711
    schema: gz_raw_data
    tables:
      - name: adwords
        identifier: raw_gz_adwords


      - name: facebook
        identifier: raw_gz_facebook


      - name: bing
        identifier: raw_gz_bing


      - name: criteo
        identifier: raw_gz_criteo